### ISSUE TITLE
Coupled Photon-Electron Transport

### ISSUE THREAD

**Issue by lkersting** [FRENSIE/FRENSIE#142]
Coupled photon-electron (forward) transport will require several features to be implemented.

- [ ] Electron emissions for photoatomic reactions.
- [ ] Photon emissions for electroatomic reactions.
- [ ] Positron transport.
- [ ] Runtime options for p-e transport.
- [ ] Particle simulation manager options for p-e transport.
