### ISSUE TITLE
Implement Adjoint Electron Analog Scattering Classes

### ISSUE THREAD

**Issue by lkersting** [FRENSIE/FRENSIE#61]
Add adjoint electron capabilities for:
- [x] Elastic Scattering Classes
- [x] Bremsstrahlung Scattering Classes
- [x] Atomic Excitation Classes
- [x] Electroionization Subshell Scattering Classes
